version: "3"

services:
  compagnie_assurance_js-apache-1:  # Utilisez le nom correct du conteneur Apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80/tcp
    volumes:
      - ./app:/var/www/html/app
      - ./apache-config.conf:/etc/apache2/conf-enabled/apache-config.conf:ro
    command: ["apache2-foreground"]
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

  mysql:
    image: mysql:latest
    ports:
      - 3307:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project_data_base
    volumes:
      - ./mysql-data:/var/opt/mysql-data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
